#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Apr 03 15:01:55 -03 2025
# SW Build 5266912 on Sun Dec 15 09:03:31 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_serdes_behav -key {Behavioral:tb_serdes:Functional:tb_serdes} -tclbatch tb_serdes.tcl -view /home/ericp/nexysvideo/hdmi_sv/tb_serdes_behav.wcfg -log simulate.log"
xsim tb_serdes_behav -key {Behavioral:tb_serdes:Functional:tb_serdes} -tclbatch tb_serdes.tcl -view /home/ericp/nexysvideo/hdmi_sv/tb_serdes_behav.wcfg -log simulate.log

