#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Mar 27 15:49:09 -03 2025
# SW Build 5266912 on Sun Dec 15 09:03:31 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_rgb_deser_behav -key {Behavioral:rgb_deser:Functional:tb_rgb_deser} -tclbatch tb_rgb_deser.tcl -log simulate.log"
xsim tb_rgb_deser_behav -key {Behavioral:rgb_deser:Functional:tb_rgb_deser} -tclbatch tb_rgb_deser.tcl -log simulate.log

